@isTest  
public class APTSMD_MetadataTest 
{
    static testMethod void test(){
        Test.startTest();
        fedexComWsRateV16 x = new fedexComWsRateV16();
        //GeneralAgencyAgreementDetail
        fedexComWsRateV16.GeneralAgencyAgreementDetail gen = new fedexComWsRateV16.GeneralAgencyAgreementDetail();    
        //DestinationControlDetail
        fedexComWsRateV16.DestinationControlDetail DestinationControlDetail = new fedexComWsRateV16.DestinationControlDetail();        
        //NotificationParameter
        fedexComWsRateV16.NotificationParameter NotificationParameter = new fedexComWsRateV16.NotificationParameter();       
        //CustomLabelDetail
        fedexComWsRateV16.CustomLabelDetail CustomLabelDetail = new fedexComWsRateV16.CustomLabelDetail();   
        //Commodity
        fedexComWsRateV16.Commodity Commodity = new fedexComWsRateV16.Commodity();
        //EMailNotificationRecipient
        fedexComWsRateV16.EMailNotificationRecipient EMailNotificationRecipient = new fedexComWsRateV16.EMailNotificationRecipient();
        //InternationalControlledExportDetail
       	fedexComWsRateV16.InternationalControlledExportDetail InternationalControlledExportDetail = new fedexComWsRateV16.InternationalControlledExportDetail();
        //FreightRateDetail
        fedexComWsRateV16.FreightRateDetail FreightRateDetail = new fedexComWsRateV16.FreightRateDetail();
        //FreightServiceCenterDetail
        fedexComWsRateV16.FreightServiceCenterDetail FreightServiceCenterDetail = new fedexComWsRateV16.FreightServiceCenterDetail();
        //FreightSpecialServicePayment
        fedexComWsRateV16.FreightSpecialServicePayment FreightSpecialServicePayment = new fedexComWsRateV16.FreightSpecialServicePayment();
        //RatedPackageDetail
        fedexComWsRateV16.RatedPackageDetail RatedPackageDetail = new fedexComWsRateV16.RatedPackageDetail();
        //CodAddTransportationChargesDetail
        fedexComWsRateV16.CodAddTransportationChargesDetail CodAddTransportationChargesDetail = new fedexComWsRateV16.CodAddTransportationChargesDetail();
        //Payment
        fedexComWsRateV16.Payment Payment = new fedexComWsRateV16.Payment();
        //DocumentFormatOptionsRequested
        fedexComWsRateV16.DocumentFormatOptionsRequested DocumentFormatOptionsRequested = new fedexComWsRateV16.DocumentFormatOptionsRequested();
        //TransactionDetail
        fedexComWsRateV16.TransactionDetail TransactionDetail = new fedexComWsRateV16.TransactionDetail();
        //ExportDeclarationDetail
        fedexComWsRateV16.ExportDeclarationDetail ExportDeclarationDetail = new fedexComWsRateV16.ExportDeclarationDetail();
        //Weight
        fedexComWsRateV16.Weight Weight = new fedexComWsRateV16.Weight();
        //CustomerSpecifiedLabelDetail
        fedexComWsRateV16.CustomerSpecifiedLabelDetail CustomerSpecifiedLabelDetail = new fedexComWsRateV16.CustomerSpecifiedLabelDetail();
        
        //ShippingDocumentDispositionDetail
        fedexComWsRateV16.ShippingDocumentDispositionDetail ShippingDocumentDispositionDetail = new fedexComWsRateV16.ShippingDocumentDispositionDetail();
        //VersionId
        fedexComWsRateV16.VersionId VersionId = new fedexComWsRateV16.VersionId();
        //ShippingDocumentPrintDetail
        fedexComWsRateV16.ShippingDocumentPrintDetail ShippingDocumentPrintDetail = new fedexComWsRateV16.ShippingDocumentPrintDetail();
        //FlatbedTrailerDetail
        fedexComWsRateV16.FlatbedTrailerDetail FlatbedTrailerDetail = new fedexComWsRateV16.FlatbedTrailerDetail();
        //HazardousCommodityContent
        fedexComWsRateV16.HazardousCommodityContent HazardousCommodityContent = new fedexComWsRateV16.HazardousCommodityContent();
        //ShipmentLegRateDetail
        fedexComWsRateV16.ShipmentLegRateDetail ShipmentLegRateDetail = new fedexComWsRateV16.ShipmentLegRateDetail();
        //Party
        fedexComWsRateV16.Party Party = new fedexComWsRateV16.Party();
        //CertificateOfOriginDetail
        fedexComWsRateV16.CertificateOfOriginDetail CertificateOfOriginDetail = new fedexComWsRateV16.CertificateOfOriginDetail();
        //ShipmentConfigurationData
        fedexComWsRateV16.ShipmentConfigurationData ShipmentConfigurationData = new fedexComWsRateV16.ShipmentConfigurationData();
        //DocTabZoneSpecification
        fedexComWsRateV16.DocTabZoneSpecification DocTabZoneSpecification = new fedexComWsRateV16.DocTabZoneSpecification();
        //Notification
        fedexComWsRateV16.Notification Notification = new fedexComWsRateV16.Notification();
        //ShippingDocumentEMailDetail
        fedexComWsRateV16.ShippingDocumentEMailDetail ShippingDocumentEMailDetail = new fedexComWsRateV16.ShippingDocumentEMailDetail();
        //CommercialInvoice
        fedexComWsRateV16.CommercialInvoice CommercialInvoice = new fedexComWsRateV16.CommercialInvoice();
        //HazardousCommodityOptionDetail
        fedexComWsRateV16.HazardousCommodityOptionDetail HazardousCommodityOptionDetail = new fedexComWsRateV16.HazardousCommodityOptionDetail();
        //Dimensions
        fedexComWsRateV16.Dimensions Dimensions = new fedexComWsRateV16.Dimensions();
        //ExpressFreightDetail
        fedexComWsRateV16.ExpressFreightDetail ExpressFreightDetail = new fedexComWsRateV16.ExpressFreightDetail();
        //EMailNotificationDetail
        fedexComWsRateV16.EMailNotificationDetail EMailNotificationDetail = new fedexComWsRateV16.EMailNotificationDetail();
        //DangerousGoodsSignatory
        fedexComWsRateV16.DangerousGoodsSignatory DangerousGoodsSignatory = new fedexComWsRateV16.DangerousGoodsSignatory();
        //ConsolidationKey {
        fedexComWsRateV16.ConsolidationKey ConsolidationKey = new fedexComWsRateV16.ConsolidationKey();
        //ServiceSubOptionDetail
        fedexComWsRateV16.ServiceSubOptionDetail ServiceSubOptionDetail = new fedexComWsRateV16.ServiceSubOptionDetail();
        //RateReply
        fedexComWsRateV16.RateReply RateReply = new fedexComWsRateV16.RateReply();
        //UploadDocumentReferenceDetail
        fedexComWsRateV16.UploadDocumentReferenceDetail UploadDocumentReferenceDetail = new fedexComWsRateV16.UploadDocumentReferenceDetail();
        //LabelSpecification
        fedexComWsRateV16.LabelSpecification LabelSpecification = new fedexComWsRateV16.LabelSpecification();
        //ShippingDocumentSpecification
        fedexComWsRateV16.ShippingDocumentSpecification ShippingDocumentSpecification = new fedexComWsRateV16.ShippingDocumentSpecification();
        //RateDiscount
        fedexComWsRateV16.RateDiscount RateDiscount = new fedexComWsRateV16.RateDiscount();
        //RateReplyDetail
        fedexComWsRateV16.RateReplyDetail RateReplyDetail = new fedexComWsRateV16.RateReplyDetail();
        //ExpressFreightDetailContact
        fedexComWsRateV16.ExpressFreightDetailContact ExpressFreightDetailContact = new fedexComWsRateV16.ExpressFreightDetailContact();
        //ReturnShipmentDetail
        fedexComWsRateV16.ReturnShipmentDetail ReturnShipmentDetail = new fedexComWsRateV16.ReturnShipmentDetail();
        //ShipmentSpecialServicesRequested
        fedexComWsRateV16.ShipmentSpecialServicesRequested ShipmentSpecialServicesRequested = new fedexComWsRateV16.ShipmentSpecialServicesRequested();
        //NaftaCertificateOfOriginDetail
        fedexComWsRateV16.NaftaCertificateOfOriginDetail NaftaCertificateOfOriginDetail = new fedexComWsRateV16.NaftaCertificateOfOriginDetail();
        //VariableHandlingChargeDetail
        fedexComWsRateV16.VariableHandlingChargeDetail VariableHandlingChargeDetail = new fedexComWsRateV16.VariableHandlingChargeDetail();
        //CustomDocumentDetail
        fedexComWsRateV16.CustomDocumentDetail CustomDocumentDetail = new fedexComWsRateV16.CustomDocumentDetail();
        //ShippingDocumentEMailRecipient
        fedexComWsRateV16.ShippingDocumentEMailRecipient ShippingDocumentEMailRecipient = new fedexComWsRateV16.ShippingDocumentEMailRecipient();
        //DelayDetail
        fedexComWsRateV16.DelayDetail DelayDetail = new fedexComWsRateV16.DelayDetail();
        //EdtTaxDetail
        fedexComWsRateV16.EdtTaxDetail EdtTaxDetail = new fedexComWsRateV16.EdtTaxDetail();
        //CodDetail
        fedexComWsRateV16.CodDetail CodDetail = new fedexComWsRateV16.CodDetail();
        //CustomerReference
        fedexComWsRateV16.CustomerReference CustomerReference = new fedexComWsRateV16.CustomerReference();
        //Money
        fedexComWsRateV16.Money Money = new fedexComWsRateV16.Money();
        //Volume
        fedexComWsRateV16.Volume Volume = new fedexComWsRateV16.Volume();
        //ShippingDocumentFormat
        fedexComWsRateV16.ShippingDocumentFormat ShippingDocumentFormat = new fedexComWsRateV16.ShippingDocumentFormat();
        //Tax
        fedexComWsRateV16.Tax Tax = new fedexComWsRateV16.Tax();
        //HazardousCommodityDescription
        fedexComWsRateV16.HazardousCommodityDescription HazardousCommodityDescription = new fedexComWsRateV16.HazardousCommodityDescription();
        //Localization
        fedexComWsRateV16.Localization Localization = new fedexComWsRateV16.Localization();
        //CustomLabelTextEntry
        fedexComWsRateV16.CustomLabelTextEntry CustomLabelTextEntry = new fedexComWsRateV16.CustomLabelTextEntry();
        //CustomDeliveryWindowDetail
        fedexComWsRateV16.CustomDeliveryWindowDetail CustomDeliveryWindowDetail = new fedexComWsRateV16.CustomDeliveryWindowDetail();
        //HazardousCommodityPackingDetail
        fedexComWsRateV16.HazardousCommodityPackingDetail HazardousCommodityPackingDetail = new fedexComWsRateV16.HazardousCommodityPackingDetail();
        //ContentRecord
        fedexComWsRateV16.ContentRecord ContentRecord = new fedexComWsRateV16.ContentRecord();
        //CommercialInvoiceDetail
        fedexComWsRateV16.CommercialInvoiceDetail CommercialInvoiceDetail = new fedexComWsRateV16.CommercialInvoiceDetail();
        //FreightGuaranteeDetail
        fedexComWsRateV16.FreightGuaranteeDetail FreightGuaranteeDetail = new fedexComWsRateV16.FreightGuaranteeDetail();
        //DangerousGoodsContainer
        fedexComWsRateV16.DangerousGoodsContainer DangerousGoodsContainer = new fedexComWsRateV16.DangerousGoodsContainer();
        //VariableHandlingCharges
        fedexComWsRateV16.VariableHandlingCharges VariableHandlingCharges = new fedexComWsRateV16.VariableHandlingCharges();
        //ReturnEMailDetail
        fedexComWsRateV16.ReturnEMailDetail ReturnEMailDetail = new fedexComWsRateV16.ReturnEMailDetail();
        //PendingShipmentProcessingOptionsRequested
        fedexComWsRateV16.PendingShipmentProcessingOptionsRequested PendingShipmentProcessingOptionsRequested = new fedexComWsRateV16.PendingShipmentProcessingOptionsRequested();
        //Address
        fedexComWsRateV16.Address Address = new fedexComWsRateV16.Address();
        //InternationalTrafficInArmsRegulationsDetail
        fedexComWsRateV16.InternationalTrafficInArmsRegulationsDetail InternationalTrafficInArmsRegulationsDetail = new fedexComWsRateV16.InternationalTrafficInArmsRegulationsDetail();
        //TrackingId
        fedexComWsRateV16.TrackingId TrackingId = new fedexComWsRateV16.TrackingId();
        //AlcoholDetail
        fedexComWsRateV16.AlcoholDetail AlcoholDetail = new fedexComWsRateV16.AlcoholDetail();
        //CustomLabelGraphicEntry
        fedexComWsRateV16.CustomLabelGraphicEntry CustomLabelGraphicEntry = new fedexComWsRateV16.CustomLabelGraphicEntry();
        //PackageSpecialServicesRequested
        fedexComWsRateV16.PackageSpecialServicesRequested PackageSpecialServicesRequested = new fedexComWsRateV16.PackageSpecialServicesRequested();
        //EtdDetail
        fedexComWsRateV16.EtdDetail EtdDetail = new fedexComWsRateV16.EtdDetail();
        //EdtExciseCondition
        fedexComWsRateV16.EdtExciseCondition EdtExciseCondition = new fedexComWsRateV16.EdtExciseCondition();
        //FreightAddressLabelDetail
        fedexComWsRateV16.FreightAddressLabelDetail FreightAddressLabelDetail = new fedexComWsRateV16.FreightAddressLabelDetail();
        //Measure
        fedexComWsRateV16.Measure Measure = new fedexComWsRateV16.Measure();
        //FreightShipmentDetail
        fedexComWsRateV16.FreightShipmentDetail FreightShipmentDetail = new fedexComWsRateV16.FreightShipmentDetail();
        //PriorityAlertDetail
        fedexComWsRateV16.PriorityAlertDetail PriorityAlertDetail = new fedexComWsRateV16.PriorityAlertDetail();
        //EdtCommodityTax
        fedexComWsRateV16.EdtCommodityTax EdtCommodityTax = new fedexComWsRateV16.EdtCommodityTax();
        //BrokerDetail
        fedexComWsRateV16.BrokerDetail BrokerDetail = new fedexComWsRateV16.BrokerDetail();
        //RadionuclideDetail
        fedexComWsRateV16.RadionuclideDetail RadionuclideDetail = new fedexComWsRateV16.RadionuclideDetail();
        //LiabilityCoverageDetail
        fedexComWsRateV16.LiabilityCoverageDetail LiabilityCoverageDetail = new fedexComWsRateV16.LiabilityCoverageDetail();
        //ShipmentRateDetail
        fedexComWsRateV16.ShipmentRateDetail ShipmentRateDetail = new fedexComWsRateV16.ShipmentRateDetail();
        //CustomsClearanceDetail
        fedexComWsRateV16.CustomsClearanceDetail CustomsClearanceDetail = new fedexComWsRateV16.CustomsClearanceDetail();
        //HoldAtLocationDetail
        fedexComWsRateV16.HoldAtLocationDetail HoldAtLocationDetail = new fedexComWsRateV16.HoldAtLocationDetail();
        //ClientDetail
        fedexComWsRateV16.ClientDetail ClientDetail = new fedexComWsRateV16.ClientDetail();
        //HomeDeliveryPremiumDetail
        fedexComWsRateV16.HomeDeliveryPremiumDetail HomeDeliveryPremiumDetail = new fedexComWsRateV16.HomeDeliveryPremiumDetail();
        //RateRequest
        fedexComWsRateV16.RateRequest RateRequest = new fedexComWsRateV16.RateRequest();
        //AdditionalLabelsDetail
        fedexComWsRateV16.AdditionalLabelsDetail AdditionalLabelsDetail = new fedexComWsRateV16.AdditionalLabelsDetail();
        //CustomLabelPosition
        fedexComWsRateV16.CustomLabelPosition CustomLabelPosition = new fedexComWsRateV16.CustomLabelPosition();
        //DateRange
        fedexComWsRateV16.DateRange DateRange = new fedexComWsRateV16.DateRange();
        //FreightCommitDetail
        fedexComWsRateV16.FreightCommitDetail FreightCommitDetail = new fedexComWsRateV16.FreightCommitDetail();
        //FreightRateNotation
        fedexComWsRateV16.FreightRateNotation FreightRateNotation = new fedexComWsRateV16.FreightRateNotation();
        //Distance
        fedexComWsRateV16.Distance Distance = new fedexComWsRateV16.Distance();
        //CustomLabelBarcodeEntry
        fedexComWsRateV16.CustomLabelBarcodeEntry CustomLabelBarcodeEntry = new fedexComWsRateV16.CustomLabelBarcodeEntry();
        //ReturnAssociationDetail
        fedexComWsRateV16.ReturnAssociationDetail ReturnAssociationDetail = new fedexComWsRateV16.ReturnAssociationDetail();
        //ShipmentDryIceDetail
        fedexComWsRateV16.ShipmentDryIceDetail ShipmentDryIceDetail = new fedexComWsRateV16.ShipmentDryIceDetail();
        //DocTabContentZone001
        fedexComWsRateV16.DocTabContentZone001 DocTabContentZone001 = new fedexComWsRateV16.DocTabContentZone001();
        //EMailLabelDetail
        fedexComWsRateV16.EMailLabelDetail EMailLabelDetail = new fedexComWsRateV16.EMailLabelDetail();
        //RegulatoryLabelContentDetail
        fedexComWsRateV16.RegulatoryLabelContentDetail RegulatoryLabelContentDetail = new fedexComWsRateV16.RegulatoryLabelContentDetail();
        //DangerousGoodsDetail
        fedexComWsRateV16.DangerousGoodsDetail DangerousGoodsDetail = new fedexComWsRateV16.DangerousGoodsDetail();
        //RecommendedDocumentSpecification
        fedexComWsRateV16.RecommendedDocumentSpecification RecommendedDocumentSpecification = new fedexComWsRateV16.RecommendedDocumentSpecification();
        //HazardousCommodityPackagingDetail
        fedexComWsRateV16.HazardousCommodityPackagingDetail HazardousCommodityPackagingDetail = new fedexComWsRateV16.HazardousCommodityPackagingDetail();
        //FreightBaseCharge
        fedexComWsRateV16.FreightBaseCharge FreightBaseCharge = new fedexComWsRateV16.FreightBaseCharge();
        //FreightShipmentLineItem
        fedexComWsRateV16.FreightShipmentLineItem FreightShipmentLineItem = new fedexComWsRateV16.FreightShipmentLineItem();
        //RadionuclideActivity
        fedexComWsRateV16.RadionuclideActivity RadionuclideActivity = new fedexComWsRateV16.RadionuclideActivity();
        //PickupDetail
        fedexComWsRateV16.PickupDetail PickupDetail = new fedexComWsRateV16.PickupDetail();
        //ExportDetail
        fedexComWsRateV16.ExportDetail ExportDetail = new fedexComWsRateV16.ExportDetail();
        //Payor
        fedexComWsRateV16.Payor Payor = new fedexComWsRateV16.Payor();
        //DocTabContentBarcoded
        fedexComWsRateV16.DocTabContentBarcoded DocTabContentBarcoded = new fedexComWsRateV16.DocTabContentBarcoded();
        //ConfigurableLabelReferenceEntry
        fedexComWsRateV16.ConfigurableLabelReferenceEntry ConfigurableLabelReferenceEntry = new fedexComWsRateV16.ConfigurableLabelReferenceEntry();
        //SignatureOptionDetail
        fedexComWsRateV16.SignatureOptionDetail SignatureOptionDetail = new fedexComWsRateV16.SignatureOptionDetail();
        //TaxpayerIdentification
        fedexComWsRateV16.TaxpayerIdentification TaxpayerIdentification = new fedexComWsRateV16.TaxpayerIdentification();
        //UploadDocumentDetail
        fedexComWsRateV16.UploadDocumentDetail UploadDocumentDetail = new fedexComWsRateV16.UploadDocumentDetail();
        //RadioactivityDetail
        fedexComWsRateV16.RadioactivityDetail RadioactivityDetail = new fedexComWsRateV16.RadioactivityDetail();
        //EMailRecipient
        fedexComWsRateV16.EMailRecipient EMailRecipient = new fedexComWsRateV16.EMailRecipient();
        //CurrencyExchangeRate
        fedexComWsRateV16.CurrencyExchangeRate CurrencyExchangeRate = new fedexComWsRateV16.CurrencyExchangeRate();
        //WebAuthenticationCredential
        fedexComWsRateV16.WebAuthenticationCredential WebAuthenticationCredential = new fedexComWsRateV16.WebAuthenticationCredential();
        //RequestedPackageLineItem
        fedexComWsRateV16.RequestedPackageLineItem RequestedPackageLineItem = new fedexComWsRateV16.RequestedPackageLineItem();
        //Rebate
        fedexComWsRateV16.Rebate Rebate = new fedexComWsRateV16.Rebate();
        //LinearMeasure
        fedexComWsRateV16.LinearMeasure LinearMeasure = new fedexComWsRateV16.LinearMeasure();
        //Surcharge
        fedexComWsRateV16.Surcharge Surcharge = new fedexComWsRateV16.Surcharge();
        //DangerousGoodsShippersDeclarationDetail
        fedexComWsRateV16.DangerousGoodsShippersDeclarationDetail DangerousGoodsShippersDeclarationDetail = new fedexComWsRateV16.DangerousGoodsShippersDeclarationDetail();
        //CustomLabelBoxEntry
        fedexComWsRateV16.CustomLabelBoxEntry CustomLabelBoxEntry = new fedexComWsRateV16.CustomLabelBoxEntry();
        //SmartPostShipmentDetail
        fedexComWsRateV16.SmartPostShipmentDetail SmartPostShipmentDetail = new fedexComWsRateV16.SmartPostShipmentDetail();
        //NaftaProducer
        fedexComWsRateV16.NaftaProducer NaftaProducer = new fedexComWsRateV16.NaftaProducer();
        //Op900Detail
        fedexComWsRateV16.Op900Detail Op900Detail = new fedexComWsRateV16.Op900Detail();
        //RatedShipmentDetail
        fedexComWsRateV16.RatedShipmentDetail RatedShipmentDetail = new fedexComWsRateV16.RatedShipmentDetail();
        //DeliveryOnInvoiceAcceptanceDetail
        fedexComWsRateV16.DeliveryOnInvoiceAcceptanceDetail DeliveryOnInvoiceAcceptanceDetail = new fedexComWsRateV16.DeliveryOnInvoiceAcceptanceDetail();
        //PackageRateDetail
        fedexComWsRateV16.PackageRateDetail PackageRateDetail = new fedexComWsRateV16.PackageRateDetail();
        //RecipientCustomsId
        fedexComWsRateV16.RecipientCustomsId RecipientCustomsId = new fedexComWsRateV16.RecipientCustomsId();
        //CustomerImageUsage
        fedexComWsRateV16.CustomerImageUsage CustomerImageUsage = new fedexComWsRateV16.CustomerImageUsage();
        //ContactAndAddress
        fedexComWsRateV16.ContactAndAddress ContactAndAddress = new fedexComWsRateV16.ContactAndAddress();
        //PendingShipmentDetail
        fedexComWsRateV16.PendingShipmentDetail PendingShipmentDetail = new fedexComWsRateV16.PendingShipmentDetail();
        //CommitDetail
        fedexComWsRateV16.CommitDetail CommitDetail = new fedexComWsRateV16.CommitDetail();
        //Rma
        fedexComWsRateV16.Rma Rma = new fedexComWsRateV16.Rma();
        //CustomsOptionDetail
        fedexComWsRateV16.CustomsOptionDetail CustomsOptionDetail = new fedexComWsRateV16.CustomsOptionDetail();
        //Contact
        fedexComWsRateV16.Contact Contact = new fedexComWsRateV16.Contact();
        //WebAuthenticationDetail
        fedexComWsRateV16.WebAuthenticationDetail WebAuthenticationDetail = new fedexComWsRateV16.WebAuthenticationDetail();
        //HazardousCommodityInnerReceptacleDetail
        fedexComWsRateV16.HazardousCommodityInnerReceptacleDetail HazardousCommodityInnerReceptacleDetail = new fedexComWsRateV16.HazardousCommodityInnerReceptacleDetail();
        //RequestedShipment
        fedexComWsRateV16.RequestedShipment RequestedShipment = new fedexComWsRateV16.RequestedShipment();
        //EmailOptionsRequested
        fedexComWsRateV16.EmailOptionsRequested EmailOptionsRequested = new fedexComWsRateV16.EmailOptionsRequested();
        //HazardousCommodityQuantityDetail
        fedexComWsRateV16.HazardousCommodityQuantityDetail HazardousCommodityQuantityDetail = new fedexComWsRateV16.HazardousCommodityQuantityDetail();
        //ReturnInstructionsDetail
        fedexComWsRateV16.ReturnInstructionsDetail ReturnInstructionsDetail = new fedexComWsRateV16.ReturnInstructionsDetail();
        //NaftaCommodityDetail
        fedexComWsRateV16.NaftaCommodityDetail NaftaCommodityDetail = new fedexComWsRateV16.NaftaCommodityDetail();
        //DocTabContent
        fedexComWsRateV16.DocTabContent DocTabContent = new fedexComWsRateV16.DocTabContent();
        //RateServicePort
        fedexComWsRateV16.RateServicePort RateServicePort = new fedexComWsRateV16.RateServicePort();
        Test.stopTest();
    }



}