public without sharing  class APTSMD_AddressWrapper
{
    public string Id;
    public string accountId;
    public string FirstName;
    public string LastName;
    public string Billing_City;
    public string Billing_Country;
    public string Billing_State;
    public string Billing_Street;
    public string Billing_Postal_Code;
    public string Shipping_City;//MS
    public string Shipping_Country;
    public string Shipping_State;
    public string Shipping_Street;
    public string Shipping_Postal_Code;
    public string Email;
    public string Phone;
    public string Fax;
    public string Company;
    public String CardNumber;
    public String SavedCard;
    public String SubString;

    
}