@isTest
public class APTSMD_OrderDetailsTest {
    static testMethod void testCart(){
        APTSMD_OrderDetails testOrder = new APTSMD_OrderDetails();
        testOrder.FullName = 'test';
        testOrder.BillTo_Account_Id = 'test';
        testOrder.ShipTo_Account_Id = 'test';
        testOrder.accLocation_Id = 'test';
        testOrder.Shipping_Method = 'test';
        testOrder.Shipping_Method_Value = 'test';
        testOrder.Shipto_Name = 'test';
        testOrder.ShipTo_Phone = 'test';
        testOrder.ShipTo_Address = 'test';
        testOrder.Product_Code = 'test';
        testOrder.Order_Status = 'test';
        testOrder.cartId = 'test';
        testOrder.Order_Number = 'test';
        testOrder.Order_ID = 'test';
        testOrder.Bank_ID = 'test';
        testOrder.Shipto_Address1 = 'test';
        testOrder.Shipto_Address2 = 'test';
        testOrder.Shipto_City = 'test';
        testOrder.Shipto_State = 'test';
        testOrder.Shipto_Country = 'test';
        testOrder.Shipto_Zip = 'test';
        testOrder.Shipping_Instructions = 'test';
        testOrder.Card_Type = 'test';
        testOrder.Cart_ID = 'test';
        testOrder.Credit_Card_Number = 'test';
        testOrder.PocAcctNumber = 'test';
        testOrder.Payment_Type = 'test';
        testOrder.poNumber = 'test';
        testOrder.GuestShipTo_Street = 'test';
        testOrder.GuestShipTo_City = 'test';
        testOrder.GuestShipTo_State = 'test';
        testOrder.GuestShipTo_Country = 'test';
        testOrder.GuestShipTo_Code = 'test';
    }
}