@isTest

private class KAPTest {

   static testMethod void testKAPHelperFunctions() {
   
   // Start the test, this changes governor limit context to
   // that of trigger rather than test.
   test.startTest();
   
   
   
   // Add test method logic using System.assert(), System.assertEquals()

   // and System.assertNotEquals() here.

   
   // Stop the test, this changes limit context back to test from trigger.
   test.stopTest();




     }
}